### ISSUE TITLE
Great work, very module

### ISSUE THREAD

**Issue by mcanthony** [Geek-Research-Lab/MeowJS#46]
When I saw this little project I immediately thought it would make a great set of modules to use for writing tutorials/teaching JavaScript. Is that what you plan to do with it? I guess the ideal  thing to do would be use separate repositories and/or AMD/UMD them and put them on NPM. They seem to be a good candidate for that.

Otherwise I personally like the convenience of a single repo, much less hassle but maintenance wise for serious and widespread use would be somewhat of a nightmare. I just discovered Google's Axiom project https://github.com/chromium/axiom which is a really cool in browser shell that you can extend and stream resources into play (like Native Client pexe binaries, or the modules on this repository). Would be a cool combo if teaching is what your doing. It would allow people to learn about streams. micro-services based architecture, and modular programming right in the browser.

**Comment by ashumeow** [comment]
Thanks!
Just wanted to say that i am not a teacher and i don't want to be a teacher. Teacher is an amazing job, but it requires heavy patience.
I'm actually more than being called as a self-developer... kind of multi-talented which my parents always call me and so many more words too...though i used to be a little bit naughty brat in my home...
Actually, this repo is not about teaching modules. But, your idea was good.
Maybe, you can fork it and do that thing.
MeowJS was an intense work... i didn't share the architecture design here, which is why it's hard to understand.
But yes, you can modify it for teaching modules.
Yet, my purpose was different though.

I was not aiming to build as NPM modules...
If i wanted to build as NPM modules, then why did i take so much pain?
This was built in with an aim to run on anything "transparently without any dependency".

I don't like to always run something inside a box, but i always want to try it outside... because inside is so boring, trying outside is more fun though it's quite risky. 

Just read my codes... most of them sucks.. but i tried my best to code without any dependency and most of them -- i untangled and unextracted the linked codes of most older works which i didn't add them in credits since the work was in-pause and requires severe upgrade. Then, do combo on interconnecting all of them... If you know network layers (OSI or TCP/IP) pretty well, then you can easily relate what i was actually tried to build.. 

Micro-services? Umm.... that's cool... but, i tried to do some implementations which is something more than microservices... something just quite extended rather than exactly following same strategy or methodology.

Google's axiom is a cool combo. I just cloned it long time back..
I have been doing some recent works but i haven't shared it here though...because that is a very different one which might not be in this part...

Few days back, i undergone some problems which i can not share. So, i won't be able to do anymore opensource works and i am not ready to share anything open anymore. Sometimes, it's good to be hidden especially for people like me. I will be disappearing from all corners. So, please don't send me anymore github issues.

You can fork any of my stuffs with free will... :)
Anyways, thanks again for your time. ;)
